### ISSUE TITLE
expodapp-walletconnect

### ISSUE THREAD

**Issue by gibumkang** [ManueleNolli/ExpoDapp-WalletConnect#1]
i've been meaning to set up a expodapp-walletconnect project for quite some time. i followed your instructions but i keep receiving an 'exception thrown while executing UI block' error when running it on my iOS simulator. any thoughts as to why this is happening? it sounds like a potential issue with react-native-svg but i'm not sure what. i am quite new to react native and mobile development in general.

**Comment by ManueleNolli** [comment]
Hi @gibumkang,
Sorry for the late reply. Yes, the react-native-svg version creates a lot of problems, I hope you fixed it. 
In any case, this project uses walletconnect v1, I suggest everyone upgrade to SDK v2.
